CREATE SEQUENCE IF NOT EXISTS eventos_seq START WITH 1 INCREMENT BY 50;

CREATE TABLE doacao
(
    id                   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    data_doacao          date,
    informacao_relevante VARCHAR(255),
    doacao               SMALLINT,
    valor                DECIMAL,
    CONSTRAINT pk_doacao PRIMARY KEY (id)
);

CREATE TABLE doadores
(
    cpf        VARCHAR(255) NOT NULL,
    nome       VARCHAR(255),
    contato    VARCHAR(255),
    rua        VARCHAR(255),
    cep        VARCHAR(255),
    numero     VARCHAR(255),
    logradouro VARCHAR(255),
    CONSTRAINT pk_doadores PRIMARY KEY (cpf)
);

CREATE TABLE eventos
(
    id       BIGINT NOT NULL,
    nome     VARCHAR(255),
    objetivo VARCHAR(255),
    local    VARCHAR(255),
    data     VARCHAR(255),
    CONSTRAINT pk_eventos PRIMARY KEY (id)
);

CREATE TABLE ongs
(
    cnpj         VARCHAR(255) NOT NULL,
    nome         VARCHAR(255),
    telefone     VARCHAR(255),
    missao       VARCHAR(255),
    area_atuacao VARCHAR(255),
    ativo        BOOLEAN      NOT NULL,
    rua          VARCHAR(255),
    cep          VARCHAR(255),
    numero       VARCHAR(255),
    logradouro   VARCHAR(255),
    CONSTRAINT pk_ongs PRIMARY KEY (cnpj)
);

CREATE TABLE parceiros
(
    cnpj             VARCHAR(255) NOT NULL,
    nome             VARCHAR(255),
    tipo_de_parceria VARCHAR(255),
    CONSTRAINT pk_parceiros PRIMARY KEY (cnpj)
);

CREATE TABLE voluntarios
(
    cpf             VARCHAR(255) NOT NULL,
    nome            VARCHAR(255),
    disponibilidade VARCHAR(255),
    habilidades     VARCHAR(255),
    contato         VARCHAR(255),
    CONSTRAINT pk_voluntarios PRIMARY KEY (cpf)
);